export const Colors = {
  primary: '#0F172A',
  accent: '#10B981',
  accentLight: '#D1FAE5',
  income: '#10B981',
  expense: '#EF4444',
  expenseLight: '#FEE2E2',
  neutral: '#64748B',
  neutralLight: '#E2E8F0',
  background: '#F8FAFC',
  card: '#FFFFFF',
  text: '#0F172A',
  textSecondary: '#64748B',
  textTertiary: '#94A3B8',
  border: '#E2E8F0',
  white: '#FFFFFF',
  dark: '#0F172A',
  warning: '#F59E0B',
  warningLight: '#FEF3C7',
  info: '#3B82F6',
  infoLight: '#DBEAFE',
};

export const ScheduleCCategories = [
  { id: 'advertising', label: 'Advertising', icon: 'megaphone' },
  { id: 'car_truck', label: 'Car & Truck Expenses', icon: 'car' },
  { id: 'commissions', label: 'Commissions & Fees', icon: 'handshake' },
  { id: 'contract_labor', label: 'Contract Labor', icon: 'people' },
  { id: 'depletion', label: 'Depletion', icon: 'arrow-down' },
  { id: 'depreciation', label: 'Depreciation', icon: 'trending-down' },
  { id: 'employee_benefits', label: 'Employee Benefits', icon: 'heart' },
  { id: 'insurance', label: 'Insurance', icon: 'shield' },
  { id: 'interest', label: 'Interest', icon: 'percent' },
  { id: 'legal_professional', label: 'Legal & Professional Services', icon: 'briefcase' },
  { id: 'office_expense', label: 'Office Expense', icon: 'desktop' },
  { id: 'pension_retirement', label: 'Pension & Retirement Plans', icon: 'lock-closed' },
  { id: 'rent_lease', label: 'Rent or Lease', icon: 'home' },
  { id: 'repairs', label: 'Repairs & Maintenance', icon: 'wrench' },
  { id: 'supplies', label: 'Supplies', icon: 'shopping-bag' },
  { id: 'taxes_licenses', label: 'Taxes & Licenses', icon: 'document-text' },
  { id: 'travel', label: 'Travel & Meals', icon: 'airplane' },
  { id: 'utilities', label: 'Utilities', icon: 'bolt' },
  { id: 'wages', label: 'Wages & Salaries', icon: 'currency-dollar' },
  { id: 'other', label: 'Other', icon: 'ellipsis-horizontal' },
];

export const IncomeCategories = [
  { id: 'sales', label: 'Sales Revenue', icon: 'trending-up' },
  { id: 'services', label: 'Service Income', icon: 'briefcase' },
  { id: 'consulting', label: 'Consulting', icon: 'chatbubble' },
  { id: 'interest', label: 'Interest Income', icon: 'percent' },
  { id: 'rental', label: 'Rental Income', icon: 'home' },
  { id: 'other', label: 'Other Income', icon: 'ellipsis-horizontal' },
];
